In [53]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings

warnings.filterwarnings("ignore")
sns.set_style()
plt.rcParams["figure.figsize"] = (12, 6)

In [54]:
df = pd.read_csv("../data/processed/datos_limpios_diagnosticos.csv",
                 sep=";", encoding="latin-1")


# 1. Análisis de contenido de detalle de atención


In [55]:
atencion_prueba = df["detalle_atencion"][0]


In [56]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

## Tokenizacion de Oraciones y Palabras

In [57]:
# Tokeniza por oracion y palabras
separado_por_oracion = sent_tokenize(atencion_prueba)
separado_por_palabra = word_tokenize(atencion_prueba)

print(separado_por_oracion)
print(separado_por_palabra)

['Paciente nueva primera consulta de Linares\nderivada del HLCM.', 'paso a 3 medio (Quiere estudiar párvulos).', 'Con diagnostico de  EP critica.', 'Se intenta dilatación percutanea a los 3 ddv sin lograr apertura.', 'Se reaiza cirugia en CEC comprobandose atresia pulmonar sin CIV y VD tripartito e insuficiencia tricuspidea moderada.', 'Se realiza valvulotomia pulmonar mas plastia tricuspidea y plastia auricular el 30-9-1999(Dr. Leon).', 'Evolucionando con Estenosis Residual moderada dilatacion de cavidades derechas y fx sistolica niormal.', 'Trae RNM UC 2013:  VFD VD 108.6 ML/M2.', 'IP FR 33.7% (Examen previo 20111: 15.4%).', 'PRESENTO SINCOPE (Unico episodio) CON ESTUDIO NEGATIVO EN TIL TEST.', 'Eco hoy 12-1-16 Dr. Baraona: Estenosis pulmonar valvular y supravalvular leves con insuficiencia libre.', 'Dilatación e hipertrofia moderada del VD con fx sistolica disminuida.', 'Insuficiencia tricúspide moderada a severa.', 'Hace vida normal en gral, deporte al menos 4 veces por semana, ha 

## Filtro por StopWords

In [58]:
stop_words = stopwords.words("spanish")
atencion_sin_stopwords = [palabra for palabra in separado_por_palabra if palabra not in stop_words]
print(atencion_sin_stopwords)

['Paciente', 'nueva', 'primera', 'consulta', 'Linares', 'derivada', 'HLCM', '.', 'paso', '3', 'medio', '(', 'Quiere', 'estudiar', 'párvulos', ')', '.', 'Con', 'diagnostico', 'EP', 'critica', '.', 'Se', 'intenta', 'dilatación', 'percutanea', '3', 'ddv', 'lograr', 'apertura', '.', 'Se', 'reaiza', 'cirugia', 'CEC', 'comprobandose', 'atresia', 'pulmonar', 'CIV', 'VD', 'tripartito', 'insuficiencia', 'tricuspidea', 'moderada', '.', 'Se', 'realiza', 'valvulotomia', 'pulmonar', 'mas', 'plastia', 'tricuspidea', 'plastia', 'auricular', '30-9-1999', '(', 'Dr.', 'Leon', ')', '.', 'Evolucionando', 'Estenosis', 'Residual', 'moderada', 'dilatacion', 'cavidades', 'derechas', 'fx', 'sistolica', 'niormal', '.', 'Trae', 'RNM', 'UC', '2013', ':', 'VFD', 'VD', '108.6', 'ML/M2', '.', 'IP', 'FR', '33.7', '%', '(', 'Examen', 'previo', '20111', ':', '15.4', '%', ')', '.', 'PRESENTO', 'SINCOPE', '(', 'Unico', 'episodio', ')', 'CON', 'ESTUDIO', 'NEGATIVO', 'EN', 'TIL', 'TEST', '.', 'Eco', 'hoy', '12-1-16', 'Dr.'

## Stemming

In [59]:
# I was taking a ride in the car.
# I was riding  in the car.
# En este caso, ride y riding significan lo mismo. Con stemming se reduce a la raiz de una palabra.

In [60]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

In [61]:
palabras_prueba = ["python", "pythoner", "pythoning", "pythoned", "pythonly"]
for w in palabras_prueba:
    print(ps.stem(w))

python
python
python
python
pythonli


In [62]:
nuevo_texto = (
    "It is very important to be pythonly while you are pythoning with python. "
    "All pythoners have pythoned poorly at least once."
)

palabras = word_tokenize(nuevo_texto)
for palabra in palabras:
    print(ps.stem(palabra))

it
is
veri
import
to
be
pythonli
while
you
are
python
with
python
.
all
python
have
python
poorli
at
least
onc
.


## Part of Speech

Agrega una etiqueta a cada palabra, indicando si la palabra es un articulo, sustantivo, adjetivo,
etc.

In [63]:
import nltk

from nltk.corpus import state_union
from nltk.tokenize import PunktSentenceTokenizer

- CC: It is the conjunction of coordinating
- CD: It is a digit of cardinal
- DT: It is the determiner
- EX: Existential
- FW: It is a foreign word
- IN: Preposition and conjunction
- JJ: Adjective
- JJR and JJS: Adjective and superlative
- LS: List marker
- MD: Modal
- NN: Singular noun
- NNS, NNP, NNPS: Proper and plural noun
- PDT: Predeterminer
- WRB: Adverb of wh
- WP$: Possessive wh
- WP: Pronoun of wh
- WDT: Determiner of wp
- VBZ: Verb
- VBP, VBN, VBG, VBD, VB: Forms of verbs
- UH: Interjection
- TO: To go
- RP: Particle
- RBS, RB, RBR: Adverb
- PRP, PRP$: Pronoun personal and professional

In [64]:
palabras_con_tag = nltk.pos_tag(atencion_sin_stopwords)
print(palabras_con_tag)

[('Paciente', 'NNP'), ('nueva', 'CC'), ('primera', 'NN'), ('consulta', 'NN'), ('Linares', 'NNP'), ('derivada', 'VBZ'), ('HLCM', 'NNP'), ('.', '.'), ('paso', 'NN'), ('3', 'CD'), ('medio', 'NN'), ('(', '('), ('Quiere', 'NNP'), ('estudiar', 'RB'), ('párvulos', 'NN'), (')', ')'), ('.', '.'), ('Con', 'NNP'), ('diagnostico', 'NN'), ('EP', 'NNP'), ('critica', 'NN'), ('.', '.'), ('Se', 'NNP'), ('intenta', 'JJ'), ('dilatación', 'NN'), ('percutanea', 'NN'), ('3', 'CD'), ('ddv', 'NN'), ('lograr', 'NN'), ('apertura', 'NN'), ('.', '.'), ('Se', 'NNP'), ('reaiza', 'NN'), ('cirugia', 'NN'), ('CEC', 'NNP'), ('comprobandose', 'NN'), ('atresia', 'NN'), ('pulmonar', 'NN'), ('CIV', 'NNP'), ('VD', 'NNP'), ('tripartito', 'NN'), ('insuficiencia', 'NN'), ('tricuspidea', 'NN'), ('moderada', 'NN'), ('.', '.'), ('Se', 'NNP'), ('realiza', 'NN'), ('valvulotomia', 'NN'), ('pulmonar', 'NN'), ('mas', 'NN'), ('plastia', 'NN'), ('tricuspidea', 'NN'), ('plastia', 'NN'), ('auricular', 'JJ'), ('30-9-1999', 'JJ'), ('(', '('

## Chunking

In [65]:
chunkgram = r""""Chunk: {<NNP.?>+<NN.?>}"""
chunkParser = nltk.RegexpParser(chunkgram)
chunked = chunkParser.parse(palabras_con_tag)

In [66]:
chunked

## Chinking

Indica todo lo que se quiere dejar fuera de los chunks

In [67]:
chunkgram = r""""Chunk: {<.*>+}
                        }<VB.?|IN|DT>+{"""
chunkParser = nltk.RegexpParser(chunkgram)
chunked = chunkParser.parse(palabras_con_tag)

In [68]:
chunked

## Named Entity Recognition

Identifica entidades dentro de un texto. Las entidades corresponden a organizaciones (Un Hospital),
personas, fechas, porcentajes, localizaciones, entre otras.

In [69]:
entidades_en_texto = nltk.ne_chunk(palabras_con_tag, binary=True)

In [70]:
entidades_en_texto

## Lemmatizing

Es como el Stemming, pero las palabras finales son palabras reales.

In [71]:
from nltk.stem import WordNetLemmatizer

In [72]:
lemmatizer = WordNetLemmatizer()

In [73]:
print(lemmatizer.lemmatize("cats"))
print(lemmatizer.lemmatize("cacti"))
print(lemmatizer.lemmatize("geese"))
print(lemmatizer.lemmatize("rocks"))
print(lemmatizer.lemmatize("python"))

cat
cactus
goose
rock
python


In [74]:
print(lemmatizer.lemmatize("better", pos="a"))

good


Aqui se puede ver que better se transformo a good, ya que es un adverbio.

## WordNet

Se pueden tomar palabras y buscar sinónimos y antónimos!

In [75]:
from nltk.corpus import wordnet

In [76]:
# Se pueden buscar sinonimos de una palabra

syns = wordnet.synsets("good")
print(syns)

# Solo el nombre
print(syns[0].lemmas())

# Definicion de la palabra
print(syns[0].definition())

# Ejemplos
print(syns[0].examples())

[Synset('good.n.01'), Synset('good.n.02'), Synset('good.n.03'), Synset('commodity.n.01'), Synset('good.a.01'), Synset('full.s.06'), Synset('good.a.03'), Synset('estimable.s.02'), Synset('beneficial.s.01'), Synset('good.s.06'), Synset('good.s.07'), Synset('adept.s.01'), Synset('good.s.09'), Synset('dear.s.02'), Synset('dependable.s.04'), Synset('good.s.12'), Synset('good.s.13'), Synset('effective.s.04'), Synset('good.s.15'), Synset('good.s.16'), Synset('good.s.17'), Synset('good.s.18'), Synset('good.s.19'), Synset('good.s.20'), Synset('good.s.21'), Synset('well.r.01'), Synset('thoroughly.r.02')]
[Lemma('good.n.01.good')]
benefit
['for your own good', "what's the good of worrying?"]


In [77]:
# Se pueden buscar antonimos de una palabra

for sinonimo in syns:
    for lema in sinonimo.lemmas():        
        print(lema)
        if lema.antonyms():
            print(f"   |----{lema.antonyms()}")

Lemma('good.n.01.good')
Lemma('good.n.02.good')
   |----[Lemma('evil.n.03.evil')]
Lemma('good.n.02.goodness')
   |----[Lemma('evil.n.03.evilness')]
Lemma('good.n.03.good')
   |----[Lemma('bad.n.01.bad')]
Lemma('good.n.03.goodness')
   |----[Lemma('bad.n.01.badness')]
Lemma('commodity.n.01.commodity')
Lemma('commodity.n.01.trade_good')
Lemma('commodity.n.01.good')
Lemma('good.a.01.good')
   |----[Lemma('bad.a.01.bad')]
Lemma('full.s.06.full')
Lemma('full.s.06.good')
Lemma('good.a.03.good')
   |----[Lemma('evil.a.01.evil')]
Lemma('estimable.s.02.estimable')
Lemma('estimable.s.02.good')
Lemma('estimable.s.02.honorable')
Lemma('estimable.s.02.respectable')
Lemma('beneficial.s.01.beneficial')
Lemma('beneficial.s.01.good')
Lemma('good.s.06.good')
Lemma('good.s.07.good')
Lemma('good.s.07.just')
Lemma('good.s.07.upright')
Lemma('adept.s.01.adept')
Lemma('adept.s.01.expert')
Lemma('adept.s.01.good')
Lemma('adept.s.01.practiced')
Lemma('adept.s.01.proficient')
Lemma('adept.s.01.skillful')
Lemma(

## Bag of Words

Existen los unigramas (toma las palabras por si solo)

In [78]:
from sklearn.feature_extraction.text import CountVectorizer

In [79]:
X_train = ["I love the book book", "This is a great book", "The fit is great", "I love the shoes"]
y_train = ["BOOKS", "BOOKS", "CLOTHING", "CLOTHING"]

In [80]:
vectorizador = CountVectorizer()
resultado_vectorizado = vectorizador.fit_transform(X_train)

In [81]:
print(vectorizador.get_feature_names_out())
print(resultado_vectorizado.toarray())

['book' 'fit' 'great' 'is' 'love' 'shoes' 'the' 'this']
[[2 0 0 0 1 0 1 0]
 [1 0 1 1 0 0 0 1]
 [0 1 1 1 0 0 1 0]
 [0 0 0 0 1 1 1 0]]


In [82]:
from sklearn.svm import SVC

In [83]:
modelo = SVC(kernel="linear")
modelo.fit(resultado_vectorizado, y_train)

SVC(kernel='linear')

In [84]:
X_test = ["This is such a bad book", "I like this shoes!"]
X_test_vectores = vectorizador.transform(X_test)

In [85]:
modelo.predict(X_test_vectores)

array(['BOOKS', 'CLOTHING'], dtype='<U8')

### Bigrama

Aqui toma conjuntos de dos palabras y las hace un vector!

In [86]:
vectorizador = CountVectorizer(ngram_range=(1, 2))
resultado_vectorizado = vectorizador.fit_transform(X_train)

print(vectorizador.get_feature_names_out())
print(resultado_vectorizado.toarray())

['book' 'book book' 'fit' 'fit is' 'great' 'great book' 'is' 'is great'
 'love' 'love the' 'shoes' 'the' 'the book' 'the fit' 'the shoes' 'this'
 'this is']
[[2 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0]
 [1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1]
 [0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0]]


Uno de los problemas ocurre cuando el conjunto de prueba contiene una palabra que nunca apareció
en el conjunto de entrenamiento. En tal caso, el modelo deja de tomar en cuenta esta palabra.

## Word of Vectors

Permite agrupar palabras que semánticamente son similares, por ejemplo: "Rojo", "Azul", "Verde" todos los
agrupa en "Color". Otro ejemplo es: "Best book I've read in year", donde uno da cuenta de que "read"
siempre aparece cerca de book. Debido a la relación anterior, se genera un vector en el espacio
que agrupa estos términos juntos.

In [87]:
import spacy

In [88]:
nlp = spacy.load("es_core_news_md")

In [89]:
docs = [nlp(text) for text in X_train]
X_train_wv_vector = [X.vector for X in docs]

In [90]:
# Representa cada oracion en muchos vectores
print(docs[0].vector)

[-1.0064259e+00 -1.6258199e+00  4.4876804e+00  3.3289459e+00
 -2.4718540e+00  8.2101792e-01 -5.1946201e+00  1.2064641e+00
 -1.3980620e+00  8.2693994e-01 -3.9157993e-01  2.2446802e-01
 -6.6238201e-01 -1.0440841e+00 -9.0491998e-01 -6.4216006e-01
 -1.9177700e+00 -5.0702013e-02  1.1560360e+00  1.8432757e+00
 -1.9458120e+00 -4.6693000e-01 -3.7663999e-01  2.5869679e+00
  3.0990005e-01  5.1653284e-01  1.4603560e+00 -5.4793596e-01
 -6.8087995e-01  1.5483000e+00  5.8075207e-01 -6.4678603e-01
  1.7224920e+00  2.2718599e+00 -5.0336802e-01 -2.7211398e-01
 -3.7652197e-01 -1.0046520e+00 -2.0266001e-01  2.5467401e+00
  2.8508201e+00  6.3268000e-01 -3.9716798e-01 -8.4435403e-01
  2.3946738e+00 -8.7176597e-01  3.7880200e-01  2.2693601e+00
 -1.9013160e+00  6.6204000e-01  2.1956122e+00  1.0694139e+00
 -6.0966599e-01 -3.3156199e+00  3.0884199e+00  7.3703003e-01
 -2.0246663e+00 -3.4241802e-01  1.6318600e-01 -1.0312039e+00
  4.8672009e-02 -1.3993998e-01  2.8540001e+00  5.1595390e-01
 -9.3139984e-02 -2.62445

In [92]:
svm = SVC(kernel="linear")
svm.fit(X_train_wv_vector, y_train)

SVC(kernel='linear')

In [93]:
X_test = ["This is such an awesome book!", "This zapato is not that great"]
X_test_vectores = [nlp(text).vector for text in X_test]

In [94]:
svm.predict(X_test_vectores)

array(['BOOKS', 'CLOTHING'], dtype='<U8')

## Regexes

In [95]:
import re

In [96]:
regexp = re.compile(r"^ab[^\s]*cd$")

In [97]:
phrases = ["abcd", "xxxx", "abxxxxcd", "xxabcdxx", "abklasduoiasduoqwduocd"]
for phrase in phrases:
    if re.match(regexp, phrase):
        print(phrase)

abcd
abxxxxcd
abklasduoiasduoqwduocd


In [98]:
# ejemplo_borde = ["aaa xxabcdxx ccc"]
# for phrase in ejemplo_borde:
#     if re.match(regexp, phrase):
#         print(phrase)


# Aqui se utiliza search en vez de match. Lo que hace es buscar en cada palabra de un conjunto de strings
regexp = re.compile(r"ab[^\s]*cd")
ejemplo_borde = ["aaa xxabcdxx ccc"]
for phrase in ejemplo_borde:
    if re.search(regexp, phrase):
        print(phrase)

aaa xxabcdxx ccc


## Stemming/Lemmatization

Es una técnica para normalizar texto! Reduce todo a su forma basal. Lemmatizing garantiza que
la palabra reducida tiene sentido, mientras que stemming puede que no.

In [3]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

In [11]:
stemmer = PorterStemmer()
phrase = "Reading the books"
phrase_tokenized = word_tokenize(phrase)

stemmed_words = [stemmer.stem(palabra) for palabra in phrase_tokenized]

In [12]:
print(stemmed_words)

['read', 'the', 'book']


In [19]:
from nltk.stem import WordNetLemmatizer

lema = WordNetLemmatizer()

lema_words = [lema.lemmatize(palabra, pos="v") for palabra in phrase_tokenized]

In [20]:
print(lema_words)

['Reading', 'the', 'book']


Algo que es muy importante es que el lematizador espera que esté el Part of Speech de cada palabra.
De esa forma, permite reducir de forma más precisa cada palabra.

## Stopwords

In [21]:
from nltk.corpus import stopwords

In [24]:
stopwords_ingles = stopwords.words("english")

In [27]:
filtradas = [palabra for palabra in phrase_tokenized if palabra not in stopwords_ingles]

In [29]:
print(filtradas)

['Reading', 'books']
